/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v62.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v62.Models.All
{
    /// <summary>
    /// EdFiCourse
    /// </summary>
    [DataContract(Name = "edFi_course")]
    public partial class EdFiCourse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiCourse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiCourse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiCourse" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="courseCode">A unique alphanumeric code assigned to a course. (required).</param>
        /// <param name="identificationCodes">An unordered collection of courseIdentificationCodes. The code that identifies the organization of subject matter and related learning experiences provided for the instruction of students. (required).</param>
        /// <param name="educationOrganizationReference">educationOrganizationReference (required).</param>
        /// <param name="academicSubjectDescriptor">The intended major subject area of the course..</param>
        /// <param name="careerPathwayDescriptor">Indicates the career cluster or pathway the course is associated with as part of a CTE curriculum..</param>
        /// <param name="competencyLevels">An unordered collection of courseCompetencyLevels. The competency levels defined to rate the student for the course..</param>
        /// <param name="courseDefinedByDescriptor">Specifies whether the course was defined by the SEA, LEA, School, or national organization..</param>
        /// <param name="courseDescription">A description of the content standards and goals covered in the course. Reference may be made to state or national content standards..</param>
        /// <param name="courseGPAApplicabilityDescriptor">An indicator of whether or not the course being described is included in the computation of the student&#39;s grade point average, and if so, if it is weighted differently from regular courses..</param>
        /// <param name="courseTitle">The descriptive name given to a course of study offered in a school or other institution or organization. In departmentalized classes at the elementary, secondary, and postsecondary levels (and for staff development activities), this refers to the name by which a course is identified (e.g., American History, English III). For elementary and other non-departmentalized classes, it refers to any portion of the instruction for which a grade or report is assigned (e.g., reading, composition, spelling, and language arts). (required).</param>
        /// <param name="dateCourseAdopted">Date the course was adopted by the education agency..</param>
        /// <param name="highSchoolCourseRequirement">An indication that this course may satisfy high school graduation requirements in the course&#39;s subject area..</param>
        /// <param name="learningObjectives">An unordered collection of courseLearningObjectives. Learning objectives to be mastered in the course..</param>
        /// <param name="learningStandards">An unordered collection of courseLearningStandards. Learning standard(s) to be taught by the course..</param>
        /// <param name="levelCharacteristics">An unordered collection of courseLevelCharacteristics. The type of specific program or designation with which the course is associated (e.g., AP, IB, Dual Credit, CTE)..</param>
        /// <param name="maxCompletionsForCredit">Designates how many times the course may be taken with credit received by the student..</param>
        /// <param name="maximumAvailableCreditConversion">Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units..</param>
        /// <param name="maximumAvailableCredits">The value of credits or units of value awarded for the completion of a course..</param>
        /// <param name="maximumAvailableCreditTypeDescriptor">The type of credits or units of value awarded for the completion of a course..</param>
        /// <param name="minimumAvailableCreditConversion">Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units..</param>
        /// <param name="minimumAvailableCredits">The value of credits or units of value awarded for the completion of a course..</param>
        /// <param name="minimumAvailableCreditTypeDescriptor">The type of credits or units of value awarded for the completion of a course..</param>
        /// <param name="numberOfParts">The number of parts identified for a course. (required).</param>
        /// <param name="offeredGradeLevels">An unordered collection of courseOfferedGradeLevels. The grade levels in which the course is offered..</param>
        /// <param name="timeRequiredForCompletion">The actual or estimated number of clock minutes required for class completion. This number is especially important for career and technical education classes and may represent (in minutes) the clock hour requirement of the class..</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        /// <param name="ext">Extensions to the Course entity..</param>
        public EdFiCourse(string id = default, string courseCode = default, List<EdFiCourseIdentificationCode> identificationCodes = default, EdFiEducationOrganizationReference educationOrganizationReference = default, string academicSubjectDescriptor = default, string careerPathwayDescriptor = default, List<EdFiCourseCompetencyLevel> competencyLevels = default, string courseDefinedByDescriptor = default, string courseDescription = default, string courseGPAApplicabilityDescriptor = default, string courseTitle = default, DateOnly? dateCourseAdopted = default, bool? highSchoolCourseRequirement = default, List<EdFiCourseLearningObjective> learningObjectives = default, List<EdFiCourseLearningStandard> learningStandards = default, List<EdFiCourseLevelCharacteristic> levelCharacteristics = default, int? maxCompletionsForCredit = default, double? maximumAvailableCreditConversion = default, double? maximumAvailableCredits = default, string maximumAvailableCreditTypeDescriptor = default, double? minimumAvailableCreditConversion = default, double? minimumAvailableCredits = default, string minimumAvailableCreditTypeDescriptor = default, int numberOfParts = default, List<EdFiCourseOfferedGradeLevel> offeredGradeLevels = default, int? timeRequiredForCompletion = default, string etag = default, Object ext = default)
        {
            // to ensure "courseCode" is required (not null)
            if (courseCode == null)
            {
                throw new ArgumentNullException("courseCode is a required property for EdFiCourse and cannot be null");
            }
            this.CourseCode = courseCode;
            // to ensure "identificationCodes" is required (not null)
            if (identificationCodes == null)
            {
                throw new ArgumentNullException("identificationCodes is a required property for EdFiCourse and cannot be null");
            }
            this.IdentificationCodes = identificationCodes;
            // to ensure "educationOrganizationReference" is required (not null)
            if (educationOrganizationReference == null)
            {
                throw new ArgumentNullException("educationOrganizationReference is a required property for EdFiCourse and cannot be null");
            }
            this.EducationOrganizationReference = educationOrganizationReference;
            // to ensure "courseTitle" is required (not null)
            if (courseTitle == null)
            {
                throw new ArgumentNullException("courseTitle is a required property for EdFiCourse and cannot be null");
            }
            this.CourseTitle = courseTitle;
            this.NumberOfParts = numberOfParts;
            this.Id = id;
            this.AcademicSubjectDescriptor = academicSubjectDescriptor;
            this.CareerPathwayDescriptor = careerPathwayDescriptor;
            this.CompetencyLevels = competencyLevels;
            this.CourseDefinedByDescriptor = courseDefinedByDescriptor;
            this.CourseDescription = courseDescription;
            this.CourseGPAApplicabilityDescriptor = courseGPAApplicabilityDescriptor;
            this.DateCourseAdopted = dateCourseAdopted;
            this.HighSchoolCourseRequirement = highSchoolCourseRequirement;
            this.LearningObjectives = learningObjectives;
            this.LearningStandards = learningStandards;
            this.LevelCharacteristics = levelCharacteristics;
            this.MaxCompletionsForCredit = maxCompletionsForCredit;
            this.MaximumAvailableCreditConversion = maximumAvailableCreditConversion;
            this.MaximumAvailableCredits = maximumAvailableCredits;
            this.MaximumAvailableCreditTypeDescriptor = maximumAvailableCreditTypeDescriptor;
            this.MinimumAvailableCreditConversion = minimumAvailableCreditConversion;
            this.MinimumAvailableCredits = minimumAvailableCredits;
            this.MinimumAvailableCreditTypeDescriptor = minimumAvailableCreditTypeDescriptor;
            this.OfferedGradeLevels = offeredGradeLevels;
            this.TimeRequiredForCompletion = timeRequiredForCompletion;
            this.Etag = etag;
            this.Ext = ext;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// A unique alphanumeric code assigned to a course.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a course.</value>
        [DataMember(Name = "courseCode", IsRequired = true, EmitDefaultValue = true)]
        public string CourseCode { get; set; }

        /// <summary>
        /// An unordered collection of courseIdentificationCodes. The code that identifies the organization of subject matter and related learning experiences provided for the instruction of students.
        /// </summary>
        /// <value>An unordered collection of courseIdentificationCodes. The code that identifies the organization of subject matter and related learning experiences provided for the instruction of students.</value>
        [DataMember(Name = "identificationCodes", IsRequired = true, EmitDefaultValue = true)]
        public List<EdFiCourseIdentificationCode> IdentificationCodes { get; set; }

        /// <summary>
        /// Gets or Sets EducationOrganizationReference
        /// </summary>
        [DataMember(Name = "educationOrganizationReference", IsRequired = true, EmitDefaultValue = true)]
        public EdFiEducationOrganizationReference EducationOrganizationReference { get; set; }

        /// <summary>
        /// The intended major subject area of the course.
        /// </summary>
        /// <value>The intended major subject area of the course.</value>
        [DataMember(Name = "academicSubjectDescriptor", EmitDefaultValue = true)]
        public string AcademicSubjectDescriptor { get; set; }

        /// <summary>
        /// Indicates the career cluster or pathway the course is associated with as part of a CTE curriculum.
        /// </summary>
        /// <value>Indicates the career cluster or pathway the course is associated with as part of a CTE curriculum.</value>
        [DataMember(Name = "careerPathwayDescriptor", EmitDefaultValue = true)]
        public string CareerPathwayDescriptor { get; set; }

        /// <summary>
        /// An unordered collection of courseCompetencyLevels. The competency levels defined to rate the student for the course.
        /// </summary>
        /// <value>An unordered collection of courseCompetencyLevels. The competency levels defined to rate the student for the course.</value>
        [DataMember(Name = "competencyLevels", EmitDefaultValue = false)]
        public List<EdFiCourseCompetencyLevel> CompetencyLevels { get; set; }

        /// <summary>
        /// Specifies whether the course was defined by the SEA, LEA, School, or national organization.
        /// </summary>
        /// <value>Specifies whether the course was defined by the SEA, LEA, School, or national organization.</value>
        [DataMember(Name = "courseDefinedByDescriptor", EmitDefaultValue = true)]
        public string CourseDefinedByDescriptor { get; set; }

        /// <summary>
        /// A description of the content standards and goals covered in the course. Reference may be made to state or national content standards.
        /// </summary>
        /// <value>A description of the content standards and goals covered in the course. Reference may be made to state or national content standards.</value>
        [DataMember(Name = "courseDescription", EmitDefaultValue = true)]
        public string CourseDescription { get; set; }

        /// <summary>
        /// An indicator of whether or not the course being described is included in the computation of the student&#39;s grade point average, and if so, if it is weighted differently from regular courses.
        /// </summary>
        /// <value>An indicator of whether or not the course being described is included in the computation of the student&#39;s grade point average, and if so, if it is weighted differently from regular courses.</value>
        [DataMember(Name = "courseGPAApplicabilityDescriptor", EmitDefaultValue = true)]
        public string CourseGPAApplicabilityDescriptor { get; set; }

        /// <summary>
        /// The descriptive name given to a course of study offered in a school or other institution or organization. In departmentalized classes at the elementary, secondary, and postsecondary levels (and for staff development activities), this refers to the name by which a course is identified (e.g., American History, English III). For elementary and other non-departmentalized classes, it refers to any portion of the instruction for which a grade or report is assigned (e.g., reading, composition, spelling, and language arts).
        /// </summary>
        /// <value>The descriptive name given to a course of study offered in a school or other institution or organization. In departmentalized classes at the elementary, secondary, and postsecondary levels (and for staff development activities), this refers to the name by which a course is identified (e.g., American History, English III). For elementary and other non-departmentalized classes, it refers to any portion of the instruction for which a grade or report is assigned (e.g., reading, composition, spelling, and language arts).</value>
        [DataMember(Name = "courseTitle", IsRequired = true, EmitDefaultValue = true)]
        public string CourseTitle { get; set; }

        /// <summary>
        /// Date the course was adopted by the education agency.
        /// </summary>
        /// <value>Date the course was adopted by the education agency.</value>
        [DataMember(Name = "dateCourseAdopted", EmitDefaultValue = true)]
        public DateOnly? DateCourseAdopted { get; set; }

        /// <summary>
        /// An indication that this course may satisfy high school graduation requirements in the course&#39;s subject area.
        /// </summary>
        /// <value>An indication that this course may satisfy high school graduation requirements in the course&#39;s subject area.</value>
        [DataMember(Name = "highSchoolCourseRequirement", EmitDefaultValue = true)]
        public bool? HighSchoolCourseRequirement { get; set; }

        /// <summary>
        /// An unordered collection of courseLearningObjectives. Learning objectives to be mastered in the course.
        /// </summary>
        /// <value>An unordered collection of courseLearningObjectives. Learning objectives to be mastered in the course.</value>
        [DataMember(Name = "learningObjectives", EmitDefaultValue = false)]
        public List<EdFiCourseLearningObjective> LearningObjectives { get; set; }

        /// <summary>
        /// An unordered collection of courseLearningStandards. Learning standard(s) to be taught by the course.
        /// </summary>
        /// <value>An unordered collection of courseLearningStandards. Learning standard(s) to be taught by the course.</value>
        [DataMember(Name = "learningStandards", EmitDefaultValue = false)]
        public List<EdFiCourseLearningStandard> LearningStandards { get; set; }

        /// <summary>
        /// An unordered collection of courseLevelCharacteristics. The type of specific program or designation with which the course is associated (e.g., AP, IB, Dual Credit, CTE).
        /// </summary>
        /// <value>An unordered collection of courseLevelCharacteristics. The type of specific program or designation with which the course is associated (e.g., AP, IB, Dual Credit, CTE).</value>
        [DataMember(Name = "levelCharacteristics", EmitDefaultValue = false)]
        public List<EdFiCourseLevelCharacteristic> LevelCharacteristics { get; set; }

        /// <summary>
        /// Designates how many times the course may be taken with credit received by the student.
        /// </summary>
        /// <value>Designates how many times the course may be taken with credit received by the student.</value>
        [DataMember(Name = "maxCompletionsForCredit", EmitDefaultValue = true)]
        public int? MaxCompletionsForCredit { get; set; }

        /// <summary>
        /// Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units.
        /// </summary>
        /// <value>Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units.</value>
        [DataMember(Name = "maximumAvailableCreditConversion", EmitDefaultValue = true)]
        public double? MaximumAvailableCreditConversion { get; set; }

        /// <summary>
        /// The value of credits or units of value awarded for the completion of a course.
        /// </summary>
        /// <value>The value of credits or units of value awarded for the completion of a course.</value>
        [DataMember(Name = "maximumAvailableCredits", EmitDefaultValue = true)]
        public double? MaximumAvailableCredits { get; set; }

        /// <summary>
        /// The type of credits or units of value awarded for the completion of a course.
        /// </summary>
        /// <value>The type of credits or units of value awarded for the completion of a course.</value>
        [DataMember(Name = "maximumAvailableCreditTypeDescriptor", EmitDefaultValue = true)]
        public string MaximumAvailableCreditTypeDescriptor { get; set; }

        /// <summary>
        /// Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units.
        /// </summary>
        /// <value>Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units.</value>
        [DataMember(Name = "minimumAvailableCreditConversion", EmitDefaultValue = true)]
        public double? MinimumAvailableCreditConversion { get; set; }

        /// <summary>
        /// The value of credits or units of value awarded for the completion of a course.
        /// </summary>
        /// <value>The value of credits or units of value awarded for the completion of a course.</value>
        [DataMember(Name = "minimumAvailableCredits", EmitDefaultValue = true)]
        public double? MinimumAvailableCredits { get; set; }

        /// <summary>
        /// The type of credits or units of value awarded for the completion of a course.
        /// </summary>
        /// <value>The type of credits or units of value awarded for the completion of a course.</value>
        [DataMember(Name = "minimumAvailableCreditTypeDescriptor", EmitDefaultValue = true)]
        public string MinimumAvailableCreditTypeDescriptor { get; set; }

        /// <summary>
        /// The number of parts identified for a course.
        /// </summary>
        /// <value>The number of parts identified for a course.</value>
        [DataMember(Name = "numberOfParts", IsRequired = true, EmitDefaultValue = true)]
        public int NumberOfParts { get; set; }

        /// <summary>
        /// An unordered collection of courseOfferedGradeLevels. The grade levels in which the course is offered.
        /// </summary>
        /// <value>An unordered collection of courseOfferedGradeLevels. The grade levels in which the course is offered.</value>
        [DataMember(Name = "offeredGradeLevels", EmitDefaultValue = false)]
        public List<EdFiCourseOfferedGradeLevel> OfferedGradeLevels { get; set; }

        /// <summary>
        /// The actual or estimated number of clock minutes required for class completion. This number is especially important for career and technical education classes and may represent (in minutes) the clock hour requirement of the class.
        /// </summary>
        /// <value>The actual or estimated number of clock minutes required for class completion. This number is especially important for career and technical education classes and may represent (in minutes) the clock hour requirement of the class.</value>
        [DataMember(Name = "timeRequiredForCompletion", EmitDefaultValue = true)]
        public int? TimeRequiredForCompletion { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Extensions to the Course entity.
        /// </summary>
        /// <value>Extensions to the Course entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiCourse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CourseCode: ").Append(CourseCode).Append("\n");
            sb.Append("  IdentificationCodes: ").Append(IdentificationCodes).Append("\n");
            sb.Append("  EducationOrganizationReference: ").Append(EducationOrganizationReference).Append("\n");
            sb.Append("  AcademicSubjectDescriptor: ").Append(AcademicSubjectDescriptor).Append("\n");
            sb.Append("  CareerPathwayDescriptor: ").Append(CareerPathwayDescriptor).Append("\n");
            sb.Append("  CompetencyLevels: ").Append(CompetencyLevels).Append("\n");
            sb.Append("  CourseDefinedByDescriptor: ").Append(CourseDefinedByDescriptor).Append("\n");
            sb.Append("  CourseDescription: ").Append(CourseDescription).Append("\n");
            sb.Append("  CourseGPAApplicabilityDescriptor: ").Append(CourseGPAApplicabilityDescriptor).Append("\n");
            sb.Append("  CourseTitle: ").Append(CourseTitle).Append("\n");
            sb.Append("  DateCourseAdopted: ").Append(DateCourseAdopted).Append("\n");
            sb.Append("  HighSchoolCourseRequirement: ").Append(HighSchoolCourseRequirement).Append("\n");
            sb.Append("  LearningObjectives: ").Append(LearningObjectives).Append("\n");
            sb.Append("  LearningStandards: ").Append(LearningStandards).Append("\n");
            sb.Append("  LevelCharacteristics: ").Append(LevelCharacteristics).Append("\n");
            sb.Append("  MaxCompletionsForCredit: ").Append(MaxCompletionsForCredit).Append("\n");
            sb.Append("  MaximumAvailableCreditConversion: ").Append(MaximumAvailableCreditConversion).Append("\n");
            sb.Append("  MaximumAvailableCredits: ").Append(MaximumAvailableCredits).Append("\n");
            sb.Append("  MaximumAvailableCreditTypeDescriptor: ").Append(MaximumAvailableCreditTypeDescriptor).Append("\n");
            sb.Append("  MinimumAvailableCreditConversion: ").Append(MinimumAvailableCreditConversion).Append("\n");
            sb.Append("  MinimumAvailableCredits: ").Append(MinimumAvailableCredits).Append("\n");
            sb.Append("  MinimumAvailableCreditTypeDescriptor: ").Append(MinimumAvailableCreditTypeDescriptor).Append("\n");
            sb.Append("  NumberOfParts: ").Append(NumberOfParts).Append("\n");
            sb.Append("  OfferedGradeLevels: ").Append(OfferedGradeLevels).Append("\n");
            sb.Append("  TimeRequiredForCompletion: ").Append(TimeRequiredForCompletion).Append("\n");
            sb.Append("  Etag: ").Append(Etag).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CourseCode (string) maxLength
            if (this.CourseCode != null && this.CourseCode.Length > 60)
            {
                yield return new ValidationResult("Invalid value for CourseCode, length must be less than 60.", new [] { "CourseCode" });
            }

            // AcademicSubjectDescriptor (string) maxLength
            if (this.AcademicSubjectDescriptor != null && this.AcademicSubjectDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for AcademicSubjectDescriptor, length must be less than 306.", new [] { "AcademicSubjectDescriptor" });
            }

            // CareerPathwayDescriptor (string) maxLength
            if (this.CareerPathwayDescriptor != null && this.CareerPathwayDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for CareerPathwayDescriptor, length must be less than 306.", new [] { "CareerPathwayDescriptor" });
            }

            // CourseDefinedByDescriptor (string) maxLength
            if (this.CourseDefinedByDescriptor != null && this.CourseDefinedByDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for CourseDefinedByDescriptor, length must be less than 306.", new [] { "CourseDefinedByDescriptor" });
            }

            // CourseDescription (string) maxLength
            if (this.CourseDescription != null && this.CourseDescription.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for CourseDescription, length must be less than 1024.", new [] { "CourseDescription" });
            }

            // CourseGPAApplicabilityDescriptor (string) maxLength
            if (this.CourseGPAApplicabilityDescriptor != null && this.CourseGPAApplicabilityDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for CourseGPAApplicabilityDescriptor, length must be less than 306.", new [] { "CourseGPAApplicabilityDescriptor" });
            }

            // CourseTitle (string) maxLength
            if (this.CourseTitle != null && this.CourseTitle.Length > 60)
            {
                yield return new ValidationResult("Invalid value for CourseTitle, length must be less than 60.", new [] { "CourseTitle" });
            }

            // MaximumAvailableCreditTypeDescriptor (string) maxLength
            if (this.MaximumAvailableCreditTypeDescriptor != null && this.MaximumAvailableCreditTypeDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for MaximumAvailableCreditTypeDescriptor, length must be less than 306.", new [] { "MaximumAvailableCreditTypeDescriptor" });
            }

            // MinimumAvailableCreditTypeDescriptor (string) maxLength
            if (this.MinimumAvailableCreditTypeDescriptor != null && this.MinimumAvailableCreditTypeDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for MinimumAvailableCreditTypeDescriptor, length must be less than 306.", new [] { "MinimumAvailableCreditTypeDescriptor" });
            }

            yield break;
        }
    }

}
