// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v62.Client;

namespace EdFi.OdsApi.Sdk.v62.Models.All
{
    /// <summary>
    /// EdFiCourseLearningObjective
    /// </summary>
    public partial class EdFiCourseLearningObjective : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiCourseLearningObjective" /> class.
        /// </summary>
        /// <param name="learningObjectiveReference">learningObjectiveReference</param>
        /// <param name="ext">Extensions to the CourseLearningObjective entity.</param>
        [JsonConstructor]
        public EdFiCourseLearningObjective(EdFiLearningObjectiveReference learningObjectiveReference, Option<Object?> ext = default)
        {
            LearningObjectiveReference = learningObjectiveReference;
            ExtOption = ext;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets LearningObjectiveReference
        /// </summary>
        [JsonPropertyName("learningObjectiveReference")]
        public EdFiLearningObjectiveReference LearningObjectiveReference { get; set; }

        /// <summary>
        /// Used to track the state of Ext
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ExtOption { get; private set; }

        /// <summary>
        /// Extensions to the CourseLearningObjective entity.
        /// </summary>
        /// <value>Extensions to the CourseLearningObjective entity.</value>
        [JsonPropertyName("_ext")]
        public Object? Ext { get { return this.ExtOption; } set { this.ExtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiCourseLearningObjective {\n");
            sb.Append("  LearningObjectiveReference: ").Append(LearningObjectiveReference).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiCourseLearningObjective" />
    /// </summary>
    public class EdFiCourseLearningObjectiveJsonConverter : JsonConverter<EdFiCourseLearningObjective>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdFiCourseLearningObjective" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiCourseLearningObjective Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EdFiLearningObjectiveReference?> learningObjectiveReference = default;
            Option<Object?> ext = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "learningObjectiveReference":
                            learningObjectiveReference = new Option<EdFiLearningObjectiveReference?>(JsonSerializer.Deserialize<EdFiLearningObjectiveReference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "_ext":
                            ext = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!learningObjectiveReference.IsSet)
                throw new ArgumentException("Property is required for class EdFiCourseLearningObjective.", nameof(learningObjectiveReference));

            if (learningObjectiveReference.IsSet && learningObjectiveReference.Value == null)
                throw new ArgumentNullException(nameof(learningObjectiveReference), "Property is not nullable for class EdFiCourseLearningObjective.");

            if (ext.IsSet && ext.Value == null)
                throw new ArgumentNullException(nameof(ext), "Property is not nullable for class EdFiCourseLearningObjective.");

            return new EdFiCourseLearningObjective(learningObjectiveReference.Value!, ext);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiCourseLearningObjective" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiCourseLearningObjective"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiCourseLearningObjective edFiCourseLearningObjective, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiCourseLearningObjective, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiCourseLearningObjective" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiCourseLearningObjective"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiCourseLearningObjective edFiCourseLearningObjective, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiCourseLearningObjective.LearningObjectiveReference == null)
                throw new ArgumentNullException(nameof(edFiCourseLearningObjective.LearningObjectiveReference), "Property is required for class EdFiCourseLearningObjective.");

            if (edFiCourseLearningObjective.ExtOption.IsSet && edFiCourseLearningObjective.Ext == null)
                throw new ArgumentNullException(nameof(edFiCourseLearningObjective.Ext), "Property is required for class EdFiCourseLearningObjective.");

            writer.WritePropertyName("learningObjectiveReference");
            JsonSerializer.Serialize(writer, edFiCourseLearningObjective.LearningObjectiveReference, jsonSerializerOptions);
            if (edFiCourseLearningObjective.ExtOption.IsSet)
            {
                writer.WritePropertyName("_ext");
                JsonSerializer.Serialize(writer, edFiCourseLearningObjective.Ext, jsonSerializerOptions);
            }
        }
    }
}
