/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v62.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v62.Models.All
{
    /// <summary>
    /// EdFiReportCardStudentLearningObjective
    /// </summary>
    [DataContract(Name = "edFi_reportCardStudentLearningObjective")]
    public partial class EdFiReportCardStudentLearningObjective : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiReportCardStudentLearningObjective" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiReportCardStudentLearningObjective() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiReportCardStudentLearningObjective" /> class.
        /// </summary>
        /// <param name="studentLearningObjectiveReference">studentLearningObjectiveReference (required).</param>
        /// <param name="ext">Extensions to the ReportCardStudentLearningObjective entity..</param>
        public EdFiReportCardStudentLearningObjective(EdFiStudentLearningObjectiveReference studentLearningObjectiveReference = default, Object ext = default)
        {
            // to ensure "studentLearningObjectiveReference" is required (not null)
            if (studentLearningObjectiveReference == null)
            {
                throw new ArgumentNullException("studentLearningObjectiveReference is a required property for EdFiReportCardStudentLearningObjective and cannot be null");
            }
            this.StudentLearningObjectiveReference = studentLearningObjectiveReference;
            this.Ext = ext;
        }

        /// <summary>
        /// Gets or Sets StudentLearningObjectiveReference
        /// </summary>
        [DataMember(Name = "studentLearningObjectiveReference", IsRequired = true, EmitDefaultValue = true)]
        public EdFiStudentLearningObjectiveReference StudentLearningObjectiveReference { get; set; }

        /// <summary>
        /// Extensions to the ReportCardStudentLearningObjective entity.
        /// </summary>
        /// <value>Extensions to the ReportCardStudentLearningObjective entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiReportCardStudentLearningObjective {\n");
            sb.Append("  StudentLearningObjectiveReference: ").Append(StudentLearningObjectiveReference).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
