// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v62.Client;

namespace EdFi.OdsApi.Sdk.v62.Models.All
{
    /// <summary>
    /// EdFiLearningObjectiveAcademicSubject
    /// </summary>
    public partial class EdFiLearningObjectiveAcademicSubject : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiLearningObjectiveAcademicSubject" /> class.
        /// </summary>
        /// <param name="academicSubjectDescriptor">The description of the content or subject area of an assessment.</param>
        /// <param name="ext">Extensions to the LearningObjectiveAcademicSubject entity.</param>
        [JsonConstructor]
        public EdFiLearningObjectiveAcademicSubject(string academicSubjectDescriptor, Option<Object?> ext = default)
        {
            AcademicSubjectDescriptor = academicSubjectDescriptor;
            ExtOption = ext;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The description of the content or subject area of an assessment.
        /// </summary>
        /// <value>The description of the content or subject area of an assessment.</value>
        [JsonPropertyName("academicSubjectDescriptor")]
        public string AcademicSubjectDescriptor { get; set; }

        /// <summary>
        /// Used to track the state of Ext
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ExtOption { get; private set; }

        /// <summary>
        /// Extensions to the LearningObjectiveAcademicSubject entity.
        /// </summary>
        /// <value>Extensions to the LearningObjectiveAcademicSubject entity.</value>
        [JsonPropertyName("_ext")]
        public Object? Ext { get { return this.ExtOption; } set { this.ExtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiLearningObjectiveAcademicSubject {\n");
            sb.Append("  AcademicSubjectDescriptor: ").Append(AcademicSubjectDescriptor).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AcademicSubjectDescriptor (string) maxLength
            if (this.AcademicSubjectDescriptor != null && this.AcademicSubjectDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for AcademicSubjectDescriptor, length must be less than 306.", new [] { "AcademicSubjectDescriptor" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiLearningObjectiveAcademicSubject" />
    /// </summary>
    public class EdFiLearningObjectiveAcademicSubjectJsonConverter : JsonConverter<EdFiLearningObjectiveAcademicSubject>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdFiLearningObjectiveAcademicSubject" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiLearningObjectiveAcademicSubject Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> academicSubjectDescriptor = default;
            Option<Object?> ext = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "academicSubjectDescriptor":
                            academicSubjectDescriptor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "_ext":
                            ext = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!academicSubjectDescriptor.IsSet)
                throw new ArgumentException("Property is required for class EdFiLearningObjectiveAcademicSubject.", nameof(academicSubjectDescriptor));

            if (academicSubjectDescriptor.IsSet && academicSubjectDescriptor.Value == null)
                throw new ArgumentNullException(nameof(academicSubjectDescriptor), "Property is not nullable for class EdFiLearningObjectiveAcademicSubject.");

            if (ext.IsSet && ext.Value == null)
                throw new ArgumentNullException(nameof(ext), "Property is not nullable for class EdFiLearningObjectiveAcademicSubject.");

            return new EdFiLearningObjectiveAcademicSubject(academicSubjectDescriptor.Value!, ext);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiLearningObjectiveAcademicSubject" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiLearningObjectiveAcademicSubject"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiLearningObjectiveAcademicSubject edFiLearningObjectiveAcademicSubject, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiLearningObjectiveAcademicSubject, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiLearningObjectiveAcademicSubject" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiLearningObjectiveAcademicSubject"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiLearningObjectiveAcademicSubject edFiLearningObjectiveAcademicSubject, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiLearningObjectiveAcademicSubject.AcademicSubjectDescriptor == null)
                throw new ArgumentNullException(nameof(edFiLearningObjectiveAcademicSubject.AcademicSubjectDescriptor), "Property is required for class EdFiLearningObjectiveAcademicSubject.");

            if (edFiLearningObjectiveAcademicSubject.ExtOption.IsSet && edFiLearningObjectiveAcademicSubject.Ext == null)
                throw new ArgumentNullException(nameof(edFiLearningObjectiveAcademicSubject.Ext), "Property is required for class EdFiLearningObjectiveAcademicSubject.");

            writer.WriteString("academicSubjectDescriptor", edFiLearningObjectiveAcademicSubject.AcademicSubjectDescriptor);

            if (edFiLearningObjectiveAcademicSubject.ExtOption.IsSet)
            {
                writer.WritePropertyName("_ext");
                JsonSerializer.Serialize(writer, edFiLearningObjectiveAcademicSubject.Ext, jsonSerializerOptions);
            }
        }
    }
}
