// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v62.Client;

namespace EdFi.OdsApi.Sdk.v62.Models.All
{
    /// <summary>
    /// EdFiLearningStandardPrerequisiteLearningStandard
    /// </summary>
    public partial class EdFiLearningStandardPrerequisiteLearningStandard : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiLearningStandardPrerequisiteLearningStandard" /> class.
        /// </summary>
        /// <param name="prerequisiteLearningStandardReference">prerequisiteLearningStandardReference</param>
        /// <param name="ext">Extensions to the LearningStandardPrerequisiteLearningStandard entity.</param>
        [JsonConstructor]
        public EdFiLearningStandardPrerequisiteLearningStandard(EdFiLearningStandardReference prerequisiteLearningStandardReference, Option<Object?> ext = default)
        {
            PrerequisiteLearningStandardReference = prerequisiteLearningStandardReference;
            ExtOption = ext;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets PrerequisiteLearningStandardReference
        /// </summary>
        [JsonPropertyName("prerequisiteLearningStandardReference")]
        public EdFiLearningStandardReference PrerequisiteLearningStandardReference { get; set; }

        /// <summary>
        /// Used to track the state of Ext
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ExtOption { get; private set; }

        /// <summary>
        /// Extensions to the LearningStandardPrerequisiteLearningStandard entity.
        /// </summary>
        /// <value>Extensions to the LearningStandardPrerequisiteLearningStandard entity.</value>
        [JsonPropertyName("_ext")]
        public Object? Ext { get { return this.ExtOption; } set { this.ExtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiLearningStandardPrerequisiteLearningStandard {\n");
            sb.Append("  PrerequisiteLearningStandardReference: ").Append(PrerequisiteLearningStandardReference).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiLearningStandardPrerequisiteLearningStandard" />
    /// </summary>
    public class EdFiLearningStandardPrerequisiteLearningStandardJsonConverter : JsonConverter<EdFiLearningStandardPrerequisiteLearningStandard>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdFiLearningStandardPrerequisiteLearningStandard" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiLearningStandardPrerequisiteLearningStandard Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EdFiLearningStandardReference?> prerequisiteLearningStandardReference = default;
            Option<Object?> ext = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "prerequisiteLearningStandardReference":
                            prerequisiteLearningStandardReference = new Option<EdFiLearningStandardReference?>(JsonSerializer.Deserialize<EdFiLearningStandardReference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "_ext":
                            ext = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!prerequisiteLearningStandardReference.IsSet)
                throw new ArgumentException("Property is required for class EdFiLearningStandardPrerequisiteLearningStandard.", nameof(prerequisiteLearningStandardReference));

            if (prerequisiteLearningStandardReference.IsSet && prerequisiteLearningStandardReference.Value == null)
                throw new ArgumentNullException(nameof(prerequisiteLearningStandardReference), "Property is not nullable for class EdFiLearningStandardPrerequisiteLearningStandard.");

            if (ext.IsSet && ext.Value == null)
                throw new ArgumentNullException(nameof(ext), "Property is not nullable for class EdFiLearningStandardPrerequisiteLearningStandard.");

            return new EdFiLearningStandardPrerequisiteLearningStandard(prerequisiteLearningStandardReference.Value!, ext);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiLearningStandardPrerequisiteLearningStandard" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiLearningStandardPrerequisiteLearningStandard"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiLearningStandardPrerequisiteLearningStandard edFiLearningStandardPrerequisiteLearningStandard, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiLearningStandardPrerequisiteLearningStandard, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiLearningStandardPrerequisiteLearningStandard" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiLearningStandardPrerequisiteLearningStandard"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiLearningStandardPrerequisiteLearningStandard edFiLearningStandardPrerequisiteLearningStandard, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiLearningStandardPrerequisiteLearningStandard.PrerequisiteLearningStandardReference == null)
                throw new ArgumentNullException(nameof(edFiLearningStandardPrerequisiteLearningStandard.PrerequisiteLearningStandardReference), "Property is required for class EdFiLearningStandardPrerequisiteLearningStandard.");

            if (edFiLearningStandardPrerequisiteLearningStandard.ExtOption.IsSet && edFiLearningStandardPrerequisiteLearningStandard.Ext == null)
                throw new ArgumentNullException(nameof(edFiLearningStandardPrerequisiteLearningStandard.Ext), "Property is required for class EdFiLearningStandardPrerequisiteLearningStandard.");

            writer.WritePropertyName("prerequisiteLearningStandardReference");
            JsonSerializer.Serialize(writer, edFiLearningStandardPrerequisiteLearningStandard.PrerequisiteLearningStandardReference, jsonSerializerOptions);
            if (edFiLearningStandardPrerequisiteLearningStandard.ExtOption.IsSet)
            {
                writer.WritePropertyName("_ext");
                JsonSerializer.Serialize(writer, edFiLearningStandardPrerequisiteLearningStandard.Ext, jsonSerializerOptions);
            }
        }
    }
}
