// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v62.Client;

namespace EdFi.OdsApi.Sdk.v62.Models.All
{
    /// <summary>
    /// TrackedChangesEdFiReportCardKey
    /// </summary>
    public partial class TrackedChangesEdFiReportCardKey : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedChangesEdFiReportCardKey" /> class.
        /// </summary>
        /// <param name="educationOrganizationId">The identifier assigned to an education organization.</param>
        /// <param name="gradingPeriodDescriptor">The name of the period for which grades are reported.</param>
        /// <param name="gradingPeriodSequence">The sequential order of this period relative to other periods.</param>
        /// <param name="gradingPeriodSchoolId">The identifier assigned to a school.</param>
        /// <param name="gradingPeriodSchoolYear">The identifier for the grading period school year.</param>
        /// <param name="studentUniqueId">A unique alphanumeric code assigned to a student.</param>
        [JsonConstructor]
        public TrackedChangesEdFiReportCardKey(Option<int?> educationOrganizationId = default, Option<string?> gradingPeriodDescriptor = default, Option<int?> gradingPeriodSequence = default, Option<int?> gradingPeriodSchoolId = default, Option<int?> gradingPeriodSchoolYear = default, Option<string?> studentUniqueId = default)
        {
            EducationOrganizationIdOption = educationOrganizationId;
            GradingPeriodDescriptorOption = gradingPeriodDescriptor;
            GradingPeriodSequenceOption = gradingPeriodSequence;
            GradingPeriodSchoolIdOption = gradingPeriodSchoolId;
            GradingPeriodSchoolYearOption = gradingPeriodSchoolYear;
            StudentUniqueIdOption = studentUniqueId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EducationOrganizationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EducationOrganizationIdOption { get; private set; }

        /// <summary>
        /// The identifier assigned to an education organization.
        /// </summary>
        /// <value>The identifier assigned to an education organization.</value>
        [JsonPropertyName("educationOrganizationId")]
        public int? EducationOrganizationId { get { return this.EducationOrganizationIdOption; } set { this.EducationOrganizationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of GradingPeriodDescriptor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GradingPeriodDescriptorOption { get; private set; }

        /// <summary>
        /// The name of the period for which grades are reported.
        /// </summary>
        /// <value>The name of the period for which grades are reported.</value>
        [JsonPropertyName("gradingPeriodDescriptor")]
        public string? GradingPeriodDescriptor { get { return this.GradingPeriodDescriptorOption; } set { this.GradingPeriodDescriptorOption = new(value); } }

        /// <summary>
        /// Used to track the state of GradingPeriodSequence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> GradingPeriodSequenceOption { get; private set; }

        /// <summary>
        /// The sequential order of this period relative to other periods.
        /// </summary>
        /// <value>The sequential order of this period relative to other periods.</value>
        [JsonPropertyName("gradingPeriodSequence")]
        public int? GradingPeriodSequence { get { return this.GradingPeriodSequenceOption; } set { this.GradingPeriodSequenceOption = new(value); } }

        /// <summary>
        /// Used to track the state of GradingPeriodSchoolId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> GradingPeriodSchoolIdOption { get; private set; }

        /// <summary>
        /// The identifier assigned to a school.
        /// </summary>
        /// <value>The identifier assigned to a school.</value>
        [JsonPropertyName("gradingPeriodSchoolId")]
        public int? GradingPeriodSchoolId { get { return this.GradingPeriodSchoolIdOption; } set { this.GradingPeriodSchoolIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of GradingPeriodSchoolYear
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> GradingPeriodSchoolYearOption { get; private set; }

        /// <summary>
        /// The identifier for the grading period school year.
        /// </summary>
        /// <value>The identifier for the grading period school year.</value>
        [JsonPropertyName("gradingPeriodSchoolYear")]
        public int? GradingPeriodSchoolYear { get { return this.GradingPeriodSchoolYearOption; } set { this.GradingPeriodSchoolYearOption = new(value); } }

        /// <summary>
        /// Used to track the state of StudentUniqueId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StudentUniqueIdOption { get; private set; }

        /// <summary>
        /// A unique alphanumeric code assigned to a student.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a student.</value>
        [JsonPropertyName("studentUniqueId")]
        public string? StudentUniqueId { get { return this.StudentUniqueIdOption; } set { this.StudentUniqueIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackedChangesEdFiReportCardKey {\n");
            sb.Append("  EducationOrganizationId: ").Append(EducationOrganizationId).Append("\n");
            sb.Append("  GradingPeriodDescriptor: ").Append(GradingPeriodDescriptor).Append("\n");
            sb.Append("  GradingPeriodSequence: ").Append(GradingPeriodSequence).Append("\n");
            sb.Append("  GradingPeriodSchoolId: ").Append(GradingPeriodSchoolId).Append("\n");
            sb.Append("  GradingPeriodSchoolYear: ").Append(GradingPeriodSchoolYear).Append("\n");
            sb.Append("  StudentUniqueId: ").Append(StudentUniqueId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // GradingPeriodDescriptor (string) maxLength
            if (this.GradingPeriodDescriptor != null && this.GradingPeriodDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for GradingPeriodDescriptor, length must be less than 306.", new [] { "GradingPeriodDescriptor" });
            }

            // StudentUniqueId (string) maxLength
            if (this.StudentUniqueId != null && this.StudentUniqueId.Length > 32)
            {
                yield return new ValidationResult("Invalid value for StudentUniqueId, length must be less than 32.", new [] { "StudentUniqueId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TrackedChangesEdFiReportCardKey" />
    /// </summary>
    public class TrackedChangesEdFiReportCardKeyJsonConverter : JsonConverter<TrackedChangesEdFiReportCardKey>
    {
        /// <summary>
        /// Deserializes json to <see cref="TrackedChangesEdFiReportCardKey" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TrackedChangesEdFiReportCardKey Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> educationOrganizationId = default;
            Option<string?> gradingPeriodDescriptor = default;
            Option<int?> gradingPeriodSequence = default;
            Option<int?> gradingPeriodSchoolId = default;
            Option<int?> gradingPeriodSchoolYear = default;
            Option<string?> studentUniqueId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "educationOrganizationId":
                            educationOrganizationId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "gradingPeriodDescriptor":
                            gradingPeriodDescriptor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "gradingPeriodSequence":
                            gradingPeriodSequence = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "gradingPeriodSchoolId":
                            gradingPeriodSchoolId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "gradingPeriodSchoolYear":
                            gradingPeriodSchoolYear = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "studentUniqueId":
                            studentUniqueId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (educationOrganizationId.IsSet && educationOrganizationId.Value == null)
                throw new ArgumentNullException(nameof(educationOrganizationId), "Property is not nullable for class TrackedChangesEdFiReportCardKey.");

            if (gradingPeriodDescriptor.IsSet && gradingPeriodDescriptor.Value == null)
                throw new ArgumentNullException(nameof(gradingPeriodDescriptor), "Property is not nullable for class TrackedChangesEdFiReportCardKey.");

            if (gradingPeriodSequence.IsSet && gradingPeriodSequence.Value == null)
                throw new ArgumentNullException(nameof(gradingPeriodSequence), "Property is not nullable for class TrackedChangesEdFiReportCardKey.");

            if (gradingPeriodSchoolId.IsSet && gradingPeriodSchoolId.Value == null)
                throw new ArgumentNullException(nameof(gradingPeriodSchoolId), "Property is not nullable for class TrackedChangesEdFiReportCardKey.");

            if (gradingPeriodSchoolYear.IsSet && gradingPeriodSchoolYear.Value == null)
                throw new ArgumentNullException(nameof(gradingPeriodSchoolYear), "Property is not nullable for class TrackedChangesEdFiReportCardKey.");

            if (studentUniqueId.IsSet && studentUniqueId.Value == null)
                throw new ArgumentNullException(nameof(studentUniqueId), "Property is not nullable for class TrackedChangesEdFiReportCardKey.");

            return new TrackedChangesEdFiReportCardKey(educationOrganizationId, gradingPeriodDescriptor, gradingPeriodSequence, gradingPeriodSchoolId, gradingPeriodSchoolYear, studentUniqueId);
        }

        /// <summary>
        /// Serializes a <see cref="TrackedChangesEdFiReportCardKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackedChangesEdFiReportCardKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TrackedChangesEdFiReportCardKey trackedChangesEdFiReportCardKey, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, trackedChangesEdFiReportCardKey, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TrackedChangesEdFiReportCardKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackedChangesEdFiReportCardKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TrackedChangesEdFiReportCardKey trackedChangesEdFiReportCardKey, JsonSerializerOptions jsonSerializerOptions)
        {
            if (trackedChangesEdFiReportCardKey.GradingPeriodDescriptorOption.IsSet && trackedChangesEdFiReportCardKey.GradingPeriodDescriptor == null)
                throw new ArgumentNullException(nameof(trackedChangesEdFiReportCardKey.GradingPeriodDescriptor), "Property is required for class TrackedChangesEdFiReportCardKey.");

            if (trackedChangesEdFiReportCardKey.StudentUniqueIdOption.IsSet && trackedChangesEdFiReportCardKey.StudentUniqueId == null)
                throw new ArgumentNullException(nameof(trackedChangesEdFiReportCardKey.StudentUniqueId), "Property is required for class TrackedChangesEdFiReportCardKey.");

            if (trackedChangesEdFiReportCardKey.EducationOrganizationIdOption.IsSet)
                writer.WriteNumber("educationOrganizationId", trackedChangesEdFiReportCardKey.EducationOrganizationIdOption.Value!.Value);

            if (trackedChangesEdFiReportCardKey.GradingPeriodDescriptorOption.IsSet)
                writer.WriteString("gradingPeriodDescriptor", trackedChangesEdFiReportCardKey.GradingPeriodDescriptor);

            if (trackedChangesEdFiReportCardKey.GradingPeriodSequenceOption.IsSet)
                writer.WriteNumber("gradingPeriodSequence", trackedChangesEdFiReportCardKey.GradingPeriodSequenceOption.Value!.Value);

            if (trackedChangesEdFiReportCardKey.GradingPeriodSchoolIdOption.IsSet)
                writer.WriteNumber("gradingPeriodSchoolId", trackedChangesEdFiReportCardKey.GradingPeriodSchoolIdOption.Value!.Value);

            if (trackedChangesEdFiReportCardKey.GradingPeriodSchoolYearOption.IsSet)
                writer.WriteNumber("gradingPeriodSchoolYear", trackedChangesEdFiReportCardKey.GradingPeriodSchoolYearOption.Value!.Value);

            if (trackedChangesEdFiReportCardKey.StudentUniqueIdOption.IsSet)
                writer.WriteString("studentUniqueId", trackedChangesEdFiReportCardKey.StudentUniqueId);
        }
    }
}
